version: '3'
services:
  mongodb:
    image: prunsoli/qmaker-db:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb_data:/data/db  # 데이터 저장 볼륨
    restart: always  # 컨테이너 재시작 시 자동으로 다시 실행