name: Deploy FullStackApp to AWS

on:
  push:
    branches:
      - feature/front-mainpage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Frontend 빌드 및 S3 배포
      - name: Build and deploy frontend
        run: |
          cd frontend
          npm ci
          CI=false npm run build
          aws s3 sync build/ s3://${{ secrets.QMAKER_S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.QMAKER_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
